[build]
  command = "npm install"

[functions]
  directory = "netlify/functions"

[functions."send-hydration-reminder"]
  schedule = "0 * * * *"

[functions."send-weekly-tracking-reminder"]
  schedule = "0 * * * *"
